// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID                   uuid.UUID
	Orderid              string
	Totalamount          int64
	CreatedAt            pgtype.Timestamp
	Integratorexternalid pgtype.Text
	StatusID             int32
	KindID               int32
}

type PaymentKind struct {
	ID   int32
	Name string
}

type PaymentStatus struct {
	ID   int32
	Name string
}
