version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin@pgadmin.com
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "6752:4222"
    command: "--name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
networks:
  nats:
    name: nats
volumes:
  local_pgdata:
  pgadmin-data: