version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
networks:
  nats:
    name: nats