@orderId=01950796-e2e7-74c6-bf61-3c2fd91d9e2d
@hostName=http://localhost:8080

## Place an Order
# @name placeOrder
# @prompt customer_id Seu id de usuário
POST {{hostName}}/api/order/place
Content-Type: application/json

{
  "customer_id": "{{customer_id}}",
  "items": [
    {
      "code": "P001",
      "name": "Product 1",
      "unit_price": 10.0,
      "quantity": 2
    },
    {
      "code": "P002",
      "name": "Product 2",
      "unit_price": 15.0,
      "quantity": 1
    }
  ]
}

### Get an Order
GET {{hostName}}/api/order/{{placeOrder.response.body.order_id}}

Content-Type: application/json

### Cancel an Order
POST {{hostName}}/api/order/{{placeOrder.response.body.order_id}}/cancel
Content-Type: application/json

{
  "reason": "Customer requested cancellation"
}