// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID    uuid.UUID
	Name  string
	Price int64
}

type Order struct {
	ID         uuid.UUID
	CustomerID string
	StatusID   int32
	CreatedAt  pgtype.Timestamp
	TotalPrice int64
	Discount   pgtype.Numeric
}

type OrderItem struct {
	OrderID uuid.UUID
	ItemID  uuid.UUID
}

type Status struct {
	ID         int32
	StatusName string
}
